### PR TITLE
Summarize the data store on every document summarization

### PR DESCRIPTION
**Pull request by conradocloudera**
This makes the data store summary consistent with the documents and repeatable (vs generated every time), plus it's faster to fetch because it's saved. We might want to change later to create this when the java BE wnats (e.g. all new documents have already been indexed/summarized, so it makes sense to re-generate).

### CODE REVIEW

**Comment by jkwatson** [comment]
how difficult would it be to add a test to make sure this works, at least with the llama-index pieces?

**Comment by conradocloudera** [comment]
> how difficult would it be to add a test to make sure this works, at least with the llama-index pieces?

Good question. I think the trickiest bit would be to update the `noop` model to return something meaningful, but not exactly the same every time. We could look if returning the same thing would be fine 🤔

**Comment by jkwatson** [comment]
> > how difficult would it be to add a test to make sure this works, at least with the llama-index pieces?
> 
> Good question. I think the trickiest bit would be to update the `noop` model to return something meaningful, but not exactly the same every time. We could look if returning the same thing would be fine 🤔

I think same content would be fine for starters.

**Comment by conradocloudera** [comment]
> > > how difficult would it be to add a test to make sure this works, at least with the llama-index pieces?
> > 
> > 
> > Good question. I think the trickiest bit would be to update the `noop` model to return something meaningful, but not exactly the same every time. We could look if returning the same thing would be fine 🤔
> 
> I think same content would be fine for starters.

Seems like we were [already](https://github.com/cloudera/CML_AMP_RAG_Studio/blob/main/llm-service/app/tests/routers/index/test_doc_summaries.py#L82) testing this! The test verifies that the answer is the same. It just happens to be generated on summary creation vs on demand now.

**Review by ewilliams-cloudera — APPROVED** [review]

**Pull request merged**
